### ISSUE TITLE
Posible error en el fichero queries.md

### ISSUE THREAD

**Issue by hlafuente** [CiudadesAbiertas/vocab-sector-publico-convenios#5]
Buenos días,

Repasando el fichero queries.md en el primer ejemplo aparece la siguiente tripleta:

`?convenio esconv:numero ?numero .`

Pero esconv:numero no aparece en el owl ¿Es posible que el ejemplo no esté actualizado?

Un saludo

**Comment by ednaru** [comment]
Sí, la propiedad esconv:numero fue cambiado a esconv:identificador. Se actualizará el fichero de queries.

**Comment by ednaru** [comment]
Se actualizó queries.md con el identificador de convenio y variación de convenio
